# Generated by Django 2.0.7 on 2019-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='pretty_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
